tubesync/sync/urls.py
from django.urls import path
from .views import (DashboardView, SourcesView, SourceSyncNowView,
                    ValidateSourceView, AddSourceView,
                    SourceView, UpdateSourceView, DeleteSourceView, MediaView,
                    MediaThumbView, MediaItemView, MediaRedownloadView, MediaSkipView,
                    MediaEnableView, MediaContent, TasksView, RevokeTaskView,
                    CompletedTasksView, ResetTasks,
                    TaskScheduleView, MediaServersView, AddMediaServerView, MediaServerView,
                    DeleteMediaServerView, UpdateMediaServerView)


app_name = 'sync'


urlpatterns = [

    # Dashboard URLs

    path(
        '',
        DashboardView.as_view(),
        name='dashboard',
    ),

    # Source URLs

    path(
        'sources',
        SourcesView.as_view(),
        name='sources',
    ),

    path(
        'source-validate',
        ValidateSourceView.as_view(),
        name='validate-source',
    ),

    path(
        'source-sync-now/<uuid:pk>',
        SourceSyncNowView.as_view(),
        name='source-sync-now',
    ),

    path(
        'source-add',
        AddSourceView.as_view(),
        name='add-source',
    ),

    path(
        'source/<uuid:pk>',
        SourceView.as_view(),
        name='source',
    ),

    path(
        'source-update/<uuid:pk>',
        UpdateSourceView.as_view(),
        name='update-source',
    ),

    path(
        'source-delete/<uuid:pk>',
        DeleteSourceView.as_view(),
        name='delete-source',
    ),

    # Media URLs

    path(
        'media',
        MediaView.as_view(),
        name='media',
    ),

    path(
        'media-thumb/<uuid:pk>',
        MediaThumbView.as_view(),
        name='media-thumb',
    ),

    path(
        'media/<uuid:pk>',
        MediaItemView.as_view(),
        name='media-item',
    ),

    path(
        'media-redownload/<uuid:pk>',
        MediaRedownloadView.as_view(),
        name='redownload-media',
    ),

    path(
        'media-thumb-redownload/<uuid:pk>',
        MediaItemView.as_view(),
        name='redownload-thumb',
    ),

    path(
        'media-skip/<uuid:pk>',
        MediaSkipView.as_view(),
        name='skip-media',
    ),

    path(
        'media-enable/<uuid:pk>',
        MediaEnableView.as_view(),
        name='enable-media',
    ),

    path(
        'media-content/<uuid:pk>',
        MediaContent.as_view(),
        name='media-content',
    ),

    # Task URLs

    path(
        'tasks',
        TasksView.as_view(),
        name='tasks',
    ),

    path(
        'task/<int:pk>/cancel',
        RevokeTaskView.as_view(),
        name='revoke-task',
    ),

    path(
        'task/<int:pk>/schedule/now',
        TaskScheduleView.as_view(),
        name='run-task',
    ),

    path(
        'task/<int:pk>/schedule/<int:timestamp>',
        TaskScheduleView.as_view(),
        name='schedule-task',
    ),

    path(
        'tasks-completed',
        CompletedTasksView.as_view(),
        name='tasks-completed',
    ),

    path(
        'tasks-reset',
        ResetTasks.as_view(),
        name='reset-tasks',
    ),

    # Media Server URLs

    path(
        'mediaservers',
        MediaServersView.as_view(),
        name='mediaservers',
    ),

    path(
        'mediaserver-add/<slug:server_type>',
        AddMediaServerView.as_view(),
        name='add-mediaserver',
    ),

    path(
        'mediaserver/<int:pk>',
        MediaServerView.as_view(),
        name='mediaserver',
    ),

    path(
        'mediaserver-delete/<int:pk>',
        DeleteMediaServerView.as_view(),
        name='delete-mediaserver',
    ),

    path(
        'mediaserver-update/<int:pk>',
        UpdateMediaServerView.as_view(),
        name='update-mediaserver',
    ),

]

tubesync/tubesync/urls.py
from django.urls import path, include
from django.contrib import admin


admin.site.site_title = 'TubeSync dashboard admin'
admin.site.site_header = 'TubeSync dashboard admin'
handler404 = 'common.views.error404'
handler500 = 'common.views.error500'


urlpatterns = [

    path('admin/',
         admin.site.urls),

    path('',
         include('common.urls', namespace='common')),

    path('',
         include('sync.urls', namespace='sync')),

]

tubesync/sync/models.py
import os
import uuid
import json
import re
from collections import OrderedDict
from copy import deepcopy
from datetime import datetime, timedelta, timezone as tz
from pathlib import Path
from xml.etree import ElementTree
from django.conf import settings
from django.db import models
from django.core.exceptions import ObjectDoesNotExist, SuspiciousOperation
from django.core.files.storage import FileSystemStorage
from django.core.serializers.json import DjangoJSONEncoder
from django.core.validators import RegexValidator
from django.db.transaction import atomic
from django.utils.text import slugify
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from common.logger import log
from common.errors import NoFormatException
from common.utils import (  clean_filename, clean_emoji,
                            django_queryset_generator as qs_gen, )
from .youtube import (  get_media_info as get_youtube_media_info,
                        download_media as download_youtube_media,
                        get_channel_image_info as get_youtube_channel_image_info)
from .utils import (seconds_to_timestr, parse_media_format, filter_response,
                    write_text_file, mkdir_p, directory_and_stem, glob_quote,
                    multi_key_sort)
from .matching import ( get_best_combined_format, get_best_audio_format,
                        get_best_video_format)
from .fields import CommaSepChoiceField
from .choices import (  Val, CapChoices, Fallback, FileExtension,
                        FilterSeconds, IndexSchedule, MediaServerType,
                        MediaState, SourceResolution, SourceResolutionInteger,
                        SponsorBlock_Category, YouTube_AudioCodec,
                        YouTube_SourceType, YouTube_VideoCodec)

media_file_storage = FileSystemStorage(location=str(settings.DOWNLOAD_ROOT), base_url='/media-data/')
_srctype_dict = lambda n: dict(zip( YouTube_SourceType.values, (n,) * len(YouTube_SourceType.values) ))

class JSONEncoder(DjangoJSONEncoder):
    item_separator = ','
    key_separator = ':'

    def default(self, obj):
        try:
            iterable = iter(obj)
        except TypeError:
            pass
        else:
            return list(iterable)
        return super().default(obj)


class Source(models.Model):
    '''
        A Source is a source of media. Currently, this is either a YouTube channel
        or a YouTube playlist.
    '''

    sponsorblock_categories = CommaSepChoiceField(
        _(''),
        max_length=128,
        possible_choices=SponsorBlock_Category.choices,
        all_choice='all',
        allow_all=True,
        all_label='(All Categories)',
        default='all',
        help_text=_('Select the SponsorBlock categories that you wish to be removed from downloaded videos.')
    )
    embed_metadata = models.BooleanField(
        _('embed metadata'),
        default=False,
        help_text=_('Embed metadata from source into file')
    )
    embed_thumbnail = models.BooleanField(
        _('embed thumbnail'),
        default=False,
        help_text=_('Embed thumbnail into the file')
    )
    enable_sponsorblock = models.BooleanField(
        _('enable sponsorblock'),
        default=True,
        help_text=_('Use SponsorBlock?')
    )

    # Fontawesome icons used for the source on the front end
    ICONS = _srctype_dict('<i class="fab fa-youtube"></i>')

    # Format to use to display a URL for the source
    URLS = dict(zip(
        YouTube_SourceType.values,
        (
            'https://www.youtube.com/c/{key}',
            'https://www.youtube.com/channel/{key}',
            'https://www.youtube.com/playlist?list={key}',
        ),
    ))

    # Format used to create indexable URLs
    INDEX_URLS = dict(zip(
        YouTube_SourceType.values,
        (
            'https://www.youtube.com/c/{key}/{type}',
            'https://www.youtube.com/channel/{key}/{type}',
            'https://www.youtube.com/playlist?list={key}',
        ),
    ))

    # Callback functions to get a list of media from the source
    INDEXERS = _srctype_dict(get_youtube_media_info)

    # Field names to find the media ID used as the key when storing media
    KEY_FIELD = _srctype_dict('id')

    uuid = models.UUIDField(
        _('uuid'),
        primary_key=True,
        editable=False,
        default=uuid.uuid4,
        help_text=_('UUID of the source')
    )
    created = models.DateTimeField(
        _('created'),
        auto_now_add=True,
        db_index=True,
        help_text=_('Date and time the source was created')
    )
    last_crawl = models.DateTimeField(
        _('last crawl'),
        db_index=True,
        null=True,
        blank=True,
        help_text=_('Date and time the source was last crawled')
    )
    source_type = models.CharField(
        _('source type'),
        max_length=1,
        db_index=True,
        choices=YouTube_SourceType.choices,
        default=YouTube_SourceType.CHANNEL,
        help_text=_('Source type')
    )
    key = models.CharField(
        _('key'),
        max_length=100,
        db_index=True,
        unique=True,
        help_text=_('Source key, such as exact YouTube channel name or playlist ID')
    )
    name = models.CharField(
        _('name'),
        max_length=100,
        db_index=True,
        unique=True,
        help_text=_('Friendly name for the source, used locally in TubeSync only')
    )
    directory = models.CharField(
        _('directory'),
        max_length=100,
        db_index=True,
        unique=True,
        help_text=_('Directory name to save the media into')
    )
    media_format = models.CharField(
        _('media format'),
        max_length=200,
        default=settings.MEDIA_FORMATSTR_DEFAULT,
        help_text=_('File format to use for saving files, detailed options at bottom of page.')
    )
    index_schedule = models.IntegerField(
        _('index schedule'),
        choices=IndexSchedule.choices,
        db_index=True,
        default=IndexSchedule.EVERY_24_HOURS,
        help_text=_('Schedule of how often to index the source for new media')
    )
    download_media = models.BooleanField(
        _('download media'),
        default=True,
        help_text=_('Download media from this source, if not selected the source will only be indexed')
    )
    index_videos = models.BooleanField(
        _('index videos'),
        default=True,
        help_text=_('Index video media from this source')
    )
    index_streams = models.BooleanField(
        _('index streams'),
        default=False,
        help_text=_('Index live stream media from this source')
    )
    download_cap = models.IntegerField(
        _('download cap'),
        choices=CapChoices.choices,
        default=CapChoices.CAP_NOCAP,
        help_text=_('Do not download media older than this capped date')
    )
    delete_old_media = models.BooleanField(
        _('delete old media'),
        default=False,
        help_text=_('Delete old media after "days to keep" days?')
    )
    days_to_keep = models.PositiveSmallIntegerField(
        _('days to keep'),
        default=14,
        help_text=_('If "delete old media" is ticked, the number of days after which '
                    'to automatically delete media')
    )
    filter_text = models.CharField(
        _('filter string'),
        max_length=200,
        default='',
        blank=True,
        help_text=_('Regex compatible filter string for video titles')
    )
    filter_text_invert = models.BooleanField(
        _("invert filter text matching"),
        default=False,
        help_text="Invert filter string regex match, skip any matching titles when selected",
    )
    filter_seconds = models.PositiveIntegerField(
                _('filter seconds'),
                blank=True,
                null=True,
                help_text=_('Filter Media based on Min/Max duration. Leave blank or 0 to disable filtering')
    )
    filter_seconds_min = models.BooleanField(
        _('filter seconds min/max'),
        choices=FilterSeconds.choices,
        default=Val(FilterSeconds.MIN),
        help_text=_('When Filter Seconds is > 0, do we skip on minimum (video shorter than limit) or maximum (video '
                    'greater than maximum) video duration')
    )
    delete_removed_media = models.BooleanField(
        _('delete removed media'),
        default=False,
        help_text=_('Delete media that is no longer on this playlist')
    )
    delete_files_on_disk = models.BooleanField(
        _('delete files on disk'),
        default=False,
        help_text=_('Delete files on disk when they are removed from TubeSync')
    )
    source_resolution = models.CharField(
        _('source resolution'),
        max_length=8,
        db_index=True,
        choices=SourceResolution.choices,
        default=SourceResolution.VIDEO_1080P,
        help_text=_('Source resolution, desired video resolution to download')
    )
    source_vcodec = models.CharField(
        _('source video codec'),
        max_length=8,
        db_index=True,
        choices=list(reversed(YouTube_VideoCodec.choices)),
        default=YouTube_VideoCodec.VP9,
        help_text=_('Source video codec, desired video encoding format to download (ignored if "resolution" is audio only)')
    )
    source_acodec = models.CharField(
        _('source audio codec'),
        max_length=8,
        db_index=True,
        choices=list(reversed(YouTube_AudioCodec.choices)),
        default=YouTube_AudioCodec.OPUS,
        help_text=_('Source audio codec, desired audio encoding format to download')
    )
    prefer_60fps = models.BooleanField(
        _('prefer 60fps'),
        default=True,
        help_text=_('Where possible, prefer 60fps media for this source')
    )
    prefer_hdr = models.BooleanField(
        _('prefer hdr'),
        default=False,
        help_text=_('Where possible, prefer HDR media for this source')
    )

tubesync/sync/views/dashboard.py
import os
import pathlib
from django.conf import settings
from django.views.generic import TemplateView
from django.db import connection
from django.db.models import F, Q, Sum
from django.utils import timezone
from common.models import TaskHistory
from .utils import get_waiting_tasks
from ..models import Source, Media
from ..choices import Val, SourceResolution


class DashboardView(TemplateView):
    '''
        The dashboard shows non-interactive totals and summaries.
    '''

    template_name = 'sync/dashboard.html'

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data(*args, **kwargs)
        data['now'] = timezone.now()
        # Sources
        data['num_sources'] = Source.objects.all().count()
        data['num_video_sources'] = Source.objects.filter(
            ~Q(source_resolution=Val(SourceResolution.AUDIO))
        ).count()
        data['num_audio_sources'] = data['num_sources'] - data['num_video_sources']
        data['num_failed_sources'] = Source.objects.filter(has_failed=True).count()
        # Media
        data['num_media'] = Media.objects.all().count()
        data['num_downloaded_media'] = Media.objects.filter(downloaded=True).count()
        # Tasks
        completed_qs = TaskHistory.objects.filter(
            start_at__isnull=False,
            end_at__gt=F('start_at'),
        )
        waiting_qs = get_waiting_tasks()
        data['num_tasks'] = waiting_qs.count()
        data['num_completed_tasks'] = completed_qs.count()
        # Disk usage
        disk_usage = Media.objects.filter(
            downloaded=True, downloaded_filesize__isnull=False
        ).defer('metadata').aggregate(Sum('downloaded_filesize'))
        data['disk_usage_bytes'] = disk_usage['downloaded_filesize__sum']
        if not data['disk_usage_bytes']:
            data['disk_usage_bytes'] = 0
        if data['disk_usage_bytes'] and data['num_downloaded_media']:
            data['average_bytes_per_media'] = round(data['disk_usage_bytes'] /
                                                    data['num_downloaded_media'])
        else:
            data['average_bytes_per_media'] = 0
        # Latest downloads
        data['latest_downloads'] = Media.objects.filter(
            downloaded=True,
            download_date__isnull=False,
            downloaded_filesize__isnull=False,
        ).defer('metadata').order_by('-download_date')[:10]
        # Largest downloads
        data['largest_downloads'] = Media.objects.filter(
            downloaded=True, downloaded_filesize__isnull=False
        ).defer('metadata').order_by('-downloaded_filesize')[:10]
        # UID and GID
        data['uid'] = os.getuid()
        data['gid'] = os.getgid()
        # Config and download locations
        data['config_dir'] = str(settings.CONFIG_BASE_DIR)
        data['downloads_dir'] = str(settings.DOWNLOAD_ROOT)
        data['database_connection'] = settings.DATABASE_CONNECTION_STR
        # Add the database filesize when using db.sqlite3
        data['database_filesize'] = None
        if 'sqlite' == connection.vendor:
            db_name = str(connection.get_connection_params().get('database', ''))
            db_path = pathlib.Path(db_name) if '/' == db_name[0] else None
            if db_path:
                data['database_filesize'] = db_path.stat().st_size
        return data

tubesync/sync/templates/sync/media-enable.html
{% extends 'base.html' %}

{% block headtitle %}Enable (unskip) media - {{ media }}{% endblock %}

{% block content %}
<h1 class="title mb-4">Enable (unskip) <strong>{{ media }}</strong></h1>
<p class="mb-4">
  You can enable your previously skipped media <strong>{{ media }}</strong>. This
  will re-enable the media to be downloaded.
</p>
<form method="post" action="{% url 'sync:enable-media' pk=media.pk %}" class="simpleform">
  {% csrf_token %}
  {% include 'simpleform.html' with form=form %}
  <div class="field pt-4 has-text-centered">
    <div class="control">
      <button class="button is-primary" type="submit" name="action">
        <span class="icon"><i class="fas fa-cloud-download-alt"></i></span>
        <span>Enable and download media</span>
      </button>
    </div>
  </div>
</form>
{% endblock %}

tubesync/sync/templates/sync/media-item.html
{% extends 'base.html' %}{% load static %}{% load humanize %}{% load filters %}

{% block headtitle %}Media - {{ media.key }}{% endblock %}

{% block content %}
<h1 class="title mb-4">Media <strong>{{ media.key }}</strong> {{ download_state_icon|safe }}</h1>
<div class="mb-4">
    {% if media.title %}<h2 class="is-clipped"><strong>{{ media.title }}</strong></h2>{% endif %}
    <p class="is-clipped"><strong><a href="{{ media.url }}" target="_blank"><i class="fas fa-link"></i> {{ media.url }}</a></strong></p>
  <p class="is-clipped">Downloading to: <strong>{{ media.source.directory_path }}</strong></p>
  {% if download_state == 'downloaded' %}
    {% if media.source.is_audio %}
    <audio controls src="{% url 'sync:media-content' pk=media.pk %}"></audio>
    {% else %}
    <video controls class="is-fullwidth">
      <source src="{% url 'sync:media-content' pk=media.pk %}">
    </video>
    {% endif %}

  <p class="is-clipped"><a href="{% url 'sync:media-content' pk=media.pk %}" download="{{ media.filename }}"><strong><i class="fas fa-download"></i> Download</strong></a></p>
  {% elif media.can_download %}
  <p class="is-clipped"><a href="{% url 'sync:redownload-media' pk=media.pk %}{% querystring manual=True %}"><strong><i class="fas fa-download"></i> Begin Downloading</strong></a> (please be patient)</p>
  {% endif %}
</div>
{% if media.manual_skip %}{% include 'errorbox.html' with message='Media is marked to be skipped and will not be downloaded.' %}
{% else %}
  {% if not media.can_download %}{% include 'errorbox.html' with message='Media cannot be downloaded because it has no formats which match the source requirements.' %}{% endif %}
  {% if media.skip %}{% include 'errorbox.html' with message='This media may be skipped due to error(s) or not matching a filter condition.' %}{% endif %}
{% endif %}
{% include 'infobox.html' with message=message %}
<div class="columns">
  <div class="column is-6">
    <div class="content">
      <blockquote>
        <p>{% if media.description %}{{ media.description|truncatewords:200 }}{% else %}(Media has no description).{% endif %}</p>
      </blockquote>
    </div>
  </div>
  <div class="column is-6">
    <div class="card mediacard">
      <div class="card-image">
        <figure class="image">
          <img src="{% if media.thumb %}{% url 'sync:media-thumb' pk=media.pk %}{% else %}{% static 'images/nothumb.png' %}{% endif %}" alt="{{ media.name }}">
        </figure>
      </div>
      <div class="card-content">
        <div class="content">
          <a href="{% url 'sync:redownload-thumb' pk=media.pk %}" class="button is-small is-fullwidth">
            <span class="icon"><i class="fas fa-redo"></i></span>
            <span>Refresh thumbnail</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% if task %}
<div class="columns">
  <div class="column is-12">
    <div class="content">
      <p>
        {% if task.start_at == task.end_at %}
        <i class="fas fa-running"></i> <strong>{{ task }}</strong><br>
        <small><i class="far fa-clock"></i> Task started at <strong>{{ task.start_at|date:'Y-m-d H:i:s' }}</strong></small>
        {% else %}
        <i class="fas fa-stopwatch"></i> <strong>{{ task }}</strong><br>
        <small><i class="fas fa-redo"></i> Task will run {% if task.run_now %}<strong>immediately</strong>{% else %}at <strong>{{ task.scheduled_at|date:'Y-m-d H:i:s' }}</strong>{% endif %}</small>
        {% endif %}
      </p>
    </div>
  </div>
</div>
{% endif %}
<div class="columns">
  <div class="column is-12">
    <div class="box">
      <h2 class="title is-5 mb-4">Media Details</h2>
      <div class="content">
        <table class="table is-fullwidth is-striped">
          <tbody>
            <tr>
              <td><strong>Source</strong></td>
              <td><a href="{% url 'sync:source' pk=media.source.pk %}">{{ media.source }}</a></td>
            </tr>
            <tr>
              <td><strong>Duration</strong></td>
              <td>{{ media.duration_formatted }}</td>
            </tr>
            <tr>
              <td><strong>Published</strong></td>
              <td>{{ media.published |date:'Y-m-d H:i' }}</td>
            </tr>
            <tr>
              <td><strong>Desired format</strong></td>
              <td>{{ media.source.format_summary }}</td>
            </tr>
            <tr>
              <td><strong>Fallback</strong></td>
              <td>{{ media.source.get_fallback_display }}</td>
            </tr>
            <tr>
              <td><strong>Title</strong></td>
              <td>{{ media.title }}</td>
            </tr>
            {% if not media.source.download_media %}
            <tr>
              <td><strong>Source download?</strong></td>
              <td>{% if media.source.download_media %}<i class="fas fa-check has-text-success"></i>{% else %}<i class="fas fa-times has-text-danger"></i>{% endif %}</td>
            </tr>
            {% endif %}
            {% if media.skip %}
            <tr>
              <td><strong>Skipping?</strong></td>
              <td>{% if media.skip %}<i class="fas fa-check has-text-success"></i>{% else %}<i class="fas fa-times has-text-danger"></i>{% endif %}</td>
            </tr>
            {% else %}
            <tr>
              <td><strong>Downloaded?</strong></td>
              <td>{% if media.downloaded %}<i class="fas fa-check has-text-success"></i> {{ media.download_date |date:'Y-m-d H:i:s' }}{% else %}<i class="fas fa-times has-text-danger"></i>{% endif %}</td>
            </tr>
            {% endif %}
            {% if media.downloaded %}
            <tr>
              <td><strong>Filename</strong></td>
              <td><code>{{ filename_path.name }}</code></td>
            </tr>
            <tr>
              <td><strong>Directory</strong></td>
              <td><code>{{ media.directory_path }}</code></td>
            </tr>
            <tr>
              <td><strong>Database Filepath</strong></td>
              <td><code>{{ media_file_path }}</code>{% if media_file_path == media.filepath %} <span class="tag is-success">matched</span>{% endif %}</td>
            </tr>
            <tr>
              <td><strong>File size</strong></td>
              <td>{{ media.downloaded_filesize|bytesformat }}</td>
            </tr>
            <tr>
              <td><strong>Downloaded codecs</strong></td>
              <td>audio:{{ media.downloaded_audio_codec }}{% if media.downloaded_video_codec %}, video:{{ media.downloaded_video_codec }}{% endif %}</td>
            </tr>
            <tr>
              <td><strong>Container</strong></td>
              <td><span class="tag">{{ media.downloaded_container|upper }}</span></td>
            </tr>
            {% if media.downloaded_video_codec %}
            <tr>
              <td><strong>Downloaded FPS</strong></td>
              <td>{{ media.downloaded_fps }} FPS</td>
            </tr>
            <tr>
              <td><strong>Downloaded HDR?</strong></td>
              <td>{% if media.downloaded_hdr %}<i class="fas fa-check has-text-success"></i>{% else %}<i class="fas fa-times has-text-danger"></i>{% endif %}</td>
            </tr>
            {% endif %}
            {% else %}
            <tr>
              <td><strong>Can download?</strong></td>
              <td>{% if media.can_download %}<i class="fas fa-check has-text-success"></i>{% else %}<i class="fas fa-times has-text-danger"></i>{% endif %}</td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="box">
      <h2 class="title is-5 mb-4">Available Formats</h2>
      <div class="content">
        {% for format in media.iter_formats %}
        <div class="mb-2">
          <strong>ID: {{ format.id }}</strong>
          {% if format.vcodec|lower != 'none' %}, {{ format.format_note }} ({{ format.width }}x{{ format.height }}), fps:{{ format.fps|lower }}, video:{{ format.vcodec }} @{{ format.vbr }}k{% endif %}
          {% if format.acodec|lower != 'none' %}, audio:{{ format.acodec }} {% if format.abr %}@{{ format.abr }}k / {% endif %}{{ format.asr|intcomma }}Hz{% if format.language_code %} [{{ format.language_code }}]{% endif %}{% if format.abr %} {{ format.format_note }}{% endif %}{% endif %}
          {% if format.id == combined_format or format.id == audio_format or format.id == video_format %}<span class="tag is-success">matched</span>{% endif %}
        </div>
        {% empty %}
        <p class="has-text-grey">Media has no indexed available formats</p>
        {% endfor %}
      </div>
    </div>
    <div class="box">
      <h2 class="title is-5 mb-4">Matched Formats</h2>
      <div class="content">
        <table class="table is-fullwidth">
          <tbody>
            <tr>
              <td><strong>Combined</strong></td>
              <td><strong>{% if combined_format %}{{ combined_format }}{% if combined_format_dict.language_code %} [{{ combined_format_dict.language_code }}]{% endif %} {% if combined_exact %}<span class="tag is-success">exact match</span>{% else %}<span class="tag is-warning">fallback</span>{% endif %}{% else %}<span class="tag is-danger">no match</span>{% endif %}</strong></td>
            </tr>
            <tr>
              <td><strong>Audio</strong></td>
              <td><strong>{% if audio_format %}{{ audio_format }}{% if audio_format_dict.language_code %} [{{ audio_format_dict.language_code }}]{% endif %} {% if audio_exact %}<span class="tag is-success">exact match</span>{% else %}<span class="tag is-warning">fallback</span>{% endif %}{% else %}<span class="tag is-danger">no match</span>{% endif %}</strong></td>
            </tr>
            <tr>
              <td><strong>Video</strong></td>
              <td><strong>{% if video_format %}{{ video_format }} {% if video_exact %}<span class="tag is-success">exact match</span>{% else %}<span class="tag is-warning">fallback</span>{% endif %}{% else %}<span class="tag is-danger">no match</span>{% endif %}</strong></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% if media.downloaded %}
<div class="columns">
  <div class="column is-6">
    <a href="{% url 'sync:redownload-media' pk=media.pk %}" class="button is-primary">
      <span class="icon"><i class="fas fa-cloud-download-alt"></i></span>
      <span>Redownload media</span>
    </a>
  </div>
  <div class="column is-6">
    <a href="{% url 'sync:skip-media' pk=media.pk %}" class="button is-danger delete-button">
      <span class="icon"><i class="fas fa-times-circle"></i></span>
      <span>Delete and skip media</span>
    </a>
  </div>
</div>
{% else %}
<div class="columns">
  <div class="column is-12">
    {% if media.manual_skip %}
      <a href="{% url 'sync:enable-media' pk=media.pk %}" class="button is-primary">
        <span class="icon"><i class="fas fa-cloud-download-alt"></i></span>
        <span>Unskip media (manually)</span>
      </a>
    {% else %}
      <a href="{% url 'sync:skip-media' pk=media.pk %}" class="button is-danger delete-button">
        <span class="icon"><i class="fas fa-times-circle"></i></span>
        <span>Manually mark media to be skipped</span>
      </a>
    {% endif %}
  </div>
</div>
{% endif %}
{% endblock %}